# Generated by Django 2.2.20 on 2021-08-16 08:34

from django.db import migrations


def fill_owners_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner).all()
        owner.flats.set(flats)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210816_1100'),
    ]

    operations = [
        migrations.RunPython(fill_owners_flats)
    ]
