# Generated by Django 2.2.20 on 2021-08-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20210816_1134'),
        ('property', '0014_auto_20210816_1151'),
    ]

    operations = [
    ]
