# Generated by Django 2.2.20 on 2021-08-20 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20210820_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomplaint',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_author', to=settings.AUTH_USER_MODEL, verbose_name='Кто жаловался'),
        ),
        migrations.AlterField(
            model_name='сomplaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_with_complaint', to='property.Flat', verbose_name='Квартира, на которую жаловались'),
        ),
    ]
